/**
 * Maps country names to regions
 * Used for auto-detecting region when a country is selected during signup
 */

export const COUNTRY_TO_REGION: { [key: string]: 'African' | 'European' | 'American' | 'Asian' | 'Maghreb' | 'Other' } = {
  // Maghreb countries
  'Morocco': 'Maghreb',
  'Algeria': 'Maghreb',
  'Tunisia': 'Maghreb',
  'Libya': 'Maghreb',
  'Mauritania': 'Maghreb',
  
  // African countries
  'South Africa': 'African',
  'Nigeria': 'African',
  'Kenya': 'African',
  'Ghana': 'African',
  'Ethiopia': 'African',
  'Uganda': 'African',
  'Tanzania': 'African',
  'Zimbabwe': 'African',
  'Zambia': 'African',
  'Senegal': 'African',
  'Ivory Coast': 'African',
  'Cameroon': 'African',
  'Angola': 'African',
  'Sudan': 'African',
  'Mozambique': 'African',
  'Madagascar': 'African',
  'Mali': 'African',
  'Burkina Faso': 'African',
  'Niger': 'African',
  'Rwanda': 'African',
  'Benin': 'African',
  'Burundi': 'African',
  'Guinea': 'African',
  'South Sudan': 'African',
  'Togo': 'African',
  'Sierra Leone': 'African',
  'Liberia': 'African',
  'Central African Republic': 'African',
  'Eritrea': 'African',
  'Gambia': 'African',
  'Botswana': 'African',
  'Namibia': 'African',
  'Gabon': 'African',
  'Lesotho': 'African',
  'Guinea-Bissau': 'African',
  'Equatorial Guinea': 'African',
  'Mauritius': 'African',
  'Eswatini': 'African',
  'Djibouti': 'African',
  'Comoros': 'African',
  'Cabo Verde': 'African',
  'Cape Verde': 'African',
  'Sao Tome and Principe': 'African',
  'Seychelles': 'African',
  'Egypt': 'African',
  'Chad': 'African',
  'Somalia': 'African',
  'Malawi': 'African',
  'Congo': 'African',
  'Democratic Republic of the Congo': 'African',
  
  // European countries
  'France': 'European',
  'Germany': 'European',
  'Spain': 'European',
  'Italy': 'European',
  'United Kingdom': 'European',
  'Netherlands': 'European',
  'Belgium': 'European',
  'Portugal': 'European',
  'Greece': 'European',
  'Poland': 'European',
  'Sweden': 'European',
  'Norway': 'European',
  'Denmark': 'European',
  'Finland': 'European',
  'Switzerland': 'European',
  'Austria': 'European',
  'Ireland': 'European',
  'Czech Republic': 'European',
  'Romania': 'European',
  'Hungary': 'European',
  'Bulgaria': 'European',
  'Croatia': 'European',
  'Slovakia': 'European',
  'Slovenia': 'European',
  'Lithuania': 'European',
  'Latvia': 'European',
  'Estonia': 'European',
  'Luxembourg': 'European',
  'Malta': 'European',
  'Cyprus': 'European',
  'Iceland': 'European',
  'Serbia': 'European',
  'Bosnia and Herzegovina': 'European',
  'Albania': 'European',
  'North Macedonia': 'European',
  'Moldova': 'European',
  'Belarus': 'European',
  'Ukraine': 'European',
  'Russia': 'European',
  'Monaco': 'European',
  'Liechtenstein': 'European',
  'Andorra': 'European',
  'San Marino': 'European',
  'Vatican City': 'European',
  'Kosovo': 'European',
  'Montenegro': 'European',
  
  // American countries
  'United States': 'American',
  'Canada': 'American',
  'Mexico': 'American',
  'Brazil': 'American',
  'Argentina': 'American',
  'Chile': 'American',
  'Colombia': 'American',
  'Peru': 'American',
  'Venezuela': 'American',
  'Ecuador': 'American',
  'Guatemala': 'American',
  'Cuba': 'American',
  'Haiti': 'American',
  'Dominican Republic': 'American',
  'Honduras': 'American',
  'Nicaragua': 'American',
  'El Salvador': 'American',
  'Costa Rica': 'American',
  'Panama': 'American',
  'Jamaica': 'American',
  'Trinidad and Tobago': 'American',
  'Guyana': 'American',
  'Suriname': 'American',
  'Paraguay': 'American',
  'Uruguay': 'American',
  'Bolivia': 'American',
  'Bahamas': 'American',
  'Barbados': 'American',
  'Belize': 'American',
  'Antigua and Barbuda': 'American',
  'Saint Lucia': 'American',
  'Grenada': 'American',
  'Saint Vincent and the Grenadines': 'American',
  'Dominica': 'American',
  'Saint Kitts and Nevis': 'American',
  'Solomon Islands': 'Other',
  'Vanuatu': 'Other',
  'Samoa': 'Other',
  'Tonga': 'Other',
  'Tuvalu': 'Other',
  'Nauru': 'Other',
  'Palau': 'Other',
  'Marshall Islands': 'Other',
  'Micronesia': 'Other',
  'Kiribati': 'Other',
  
  // Asian countries
  'China': 'Asian',
  'Japan': 'Asian',
  'India': 'Asian',
  'South Korea': 'Asian',
  'North Korea': 'Asian',
  'Thailand': 'Asian',
  'Vietnam': 'Asian',
  'Philippines': 'Asian',
  'Indonesia': 'Asian',
  'Malaysia': 'Asian',
  'Singapore': 'Asian',
  'Pakistan': 'Asian',
  'Bangladesh': 'Asian',
  'Sri Lanka': 'Asian',
  'Nepal': 'Asian',
  'Myanmar': 'Asian',
  'Cambodia': 'Asian',
  'Laos': 'Asian',
  'Mongolia': 'Asian',
  'Kazakhstan': 'Asian',
  'Uzbekistan': 'Asian',
  'Turkmenistan': 'Asian',
  'Kyrgyzstan': 'Asian',
  'Tajikistan': 'Asian',
  'Afghanistan': 'Asian',
  'Iran': 'Asian',
  'Iraq': 'Asian',
  'Saudi Arabia': 'Asian',
  'United Arab Emirates': 'Asian',
  'Qatar': 'Asian',
  'Kuwait': 'Asian',
  'Bahrain': 'Asian',
  'Oman': 'Asian',
  'Yemen': 'Asian',
  'Jordan': 'Asian',
  'Lebanon': 'Asian',
  'Syria': 'Asian',
  'Israel': 'Asian',
  'Palestine': 'Asian',
  'Turkey': 'Asian',
  'Azerbaijan': 'Asian',
  'Armenia': 'Asian',
  'Georgia': 'Asian',
  'Brunei': 'Asian',
  'Bhutan': 'Asian',
  'Maldives': 'Asian',
  'Timor-Leste': 'Asian',
  'East Timor': 'Asian',
  'Taiwan': 'Asian',
  
  // Oceania (defaulting to Other)
  'Australia': 'Other',
  'New Zealand': 'Other',
  'Fiji': 'Other',
  'Papua New Guinea': 'Other',
};

/**
 * Get region for a given country name
 * @param countryName - The name of the country
 * @returns The region or 'Other' if not found
 */
export function getRegionForCountry(countryName: string): 'African' | 'European' | 'American' | 'Asian' | 'Maghreb' | 'Other' {
  // Try exact match first
  if (COUNTRY_TO_REGION[countryName]) {
    return COUNTRY_TO_REGION[countryName];
  }
  
  // Try case-insensitive match
  const countryKey = Object.keys(COUNTRY_TO_REGION).find(
    key => key.toLowerCase() === countryName.toLowerCase()
  );
  
  if (countryKey) {
    return COUNTRY_TO_REGION[countryKey];
  }
  
  // Fallback to 'Other'
  return 'Other';
}
